apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-training-app
  namespace: form-k8s-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-training-app
  template:
    metadata:
      labels:
        app: front-training-app
    spec:
      containers:
        - name: frontend
          image: axelpereira/k8s-training-test-app-front:1.1
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          env:
            - name: env
              value: dev
