kind: Deployment
apiVersion: apps/v1
metadata:
  name: back-training-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-training-app
  template:
    metadata:
      labels:
        app: back-training-app
    spec:
      priorityClassName: prod-priority
      containers:
        - name: back-training-app
          image: axelpereira/k8s-training-test-app-back:1.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "1Gi"
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: MONGO_PASSWORD
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: back-configmap
                  key: MONGO_PORT
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: back-configmap
                  key: MONGO_DB
            - name: MONGO_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: back-configmap
                  key: MONGO_HOSTNAME  
