apiVersion: v1
kind: Service
metadata:
  name: front-training-app
spec:
  selector:
    app: front-training-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
